# Generated by Django 5.0 on 2023-12-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='animal_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='approved_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied')], default='pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='latitiiude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='smoke_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
