# Generated by Django 5.0 on 2023-12-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_advertisement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='approved_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=500),
        ),
    ]
