# Generated by Django 5.0 on 2023-12-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='advertisement',
        ),
    ]
