# Generated by Django 5.0 on 2023-12-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_remove_city_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='advertisements.city'),
            preserve_default=False,
        ),
    ]
