# Generated by Django 5.0 on 2023-12-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_advertisement_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
