# Generated by Django 5.0 on 2023-12-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_advertisement_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='features',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='dish_washer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='washing_machine',
            field=models.BooleanField(default=False),
        ),
    ]
