# Generated by Django 5.0 on 2023-12-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_remove_advertisement_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='dish_washer',
            new_name='dishwasher',
        ),
    ]
