# Generated by Django 5.0 on 2023-12-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_advertisement_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_request',
            old_name='order_status',
            new_name='order_status_choice',
        ),
    ]
