# Generated by Django 5.0 on 2023-12-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0015_alter_rent_request_order_status_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='latitiiude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
