# Generated by Django 5.0 on 2023-12-23 19:14

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0003_alter_advertisement_advertisement_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_image', models.ImageField(default='images/ge.jpg', upload_to='images/')),
                ('phone_number', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('fmmale', 'Fmmale')], default=[('male', 'Male'), ('fmmale', 'Fmmale')], max_length=64)),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('language', models.CharField(choices=[('einglish', 'Einglish'), ('arabic', 'Arabic')], default=[('einglish', 'Einglish'), ('arabic', 'Arabic')], max_length=64)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=64)),
                ('id_image', models.ImageField(upload_to='images/')),
                ('validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
