# Generated by Django 5.0 on 2023-12-24 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0005_rent_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_image', models.ImageField(default='images/ge.jpg', upload_to='images/')),
                ('phone_number', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=[('Male', 'Male'), ('Female', 'Female')], max_length=64)),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('language', models.CharField(choices=[('Einglish', 'Einglish'), ('Arabic', 'Arabic')], default=[('Einglish', 'Einglish'), ('Arabic', 'Arabic')], max_length=64)),
                ('nationality', models.CharField(choices=[('Saudi', 'Saudi'), ('Emirati', 'Emirati'), ('etc', 'Etc')], default=[('Saudi', 'Saudi'), ('Emirati', 'Emirati'), ('etc', 'Etc')], max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=64)),
                ('id_image', models.ImageField(upload_to='images/')),
                ('validated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
