# Generated by Django 5.0 on 2023-12-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('Saudi', 'Saudi'), ('Non-Saudi', 'Non-Saudi')], max_length=64),
        ),
    ]
